global:
  storageClass: 'kubermatic-fast'

redis:
  enabled: true
  fullnameOverride: paperless-ngx-redis
  architecture: 'standalone'

postgresql:
  enabled: true
  fullnameOverride: paperless-ngx-postgresql
  auth:
    existingSecret: postgres-password
    username: paperless-ngx
    database: paperless-ngx